### ISSUE TITLE
当我使用HTTPS时，有些内容无法正常显示~

### ISSUE THREAD

**Issue by hyj223** [Huxpro/huxpro.github.io#19]
[http://huangxuan.me](http://huangxuan.me)
[https://huangxuan.me](https://huangxuan.me)  
HAVE HTTPS:
![2cdff664-da1d-41ed-abf0-698d41e35f7b](https://cloud.githubusercontent.com/assets/5220563/11355508/7a878fbe-9290-11e5-8982-475924c25564.png)

NO HTTPS:
![fc7472f9-82e2-48c0-b2ec-4a484da2b00c](https://cloud.githubusercontent.com/assets/5220563/11355542/bce60106-9290-11e5-8d37-3821b7951c74.png)

**Comment by Huxpro** [comment]
@hyj223 yep, this issue is duplicated with [issue#11](https://github.com/Huxpro/huxpro.github.io/issues/11).

I am so so sorry that the CDN I choose to serve the icon font is not support HTTPS yet, so we will get this error when page loaded over HTTPS: 
```
Mixed Content: The page at 'https://huangxuan.me/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
```

Em...gonna to switch to a more modern CDN in near update

**Comment by hyj223** [comment]
This theme is very good~
I hope you can make it better~
