### ISSUE TITLE
开源模板

### ISSUE THREAD

**Issue by nephen** [Huxpro/huxpro.github.io#56]
我在想怎么将你这个模板变成真正的开源模板，即你这边的仓库更新后，我自己的仓库也能从你那获取更新，而自己写的文章及个人设置不会变。请问有木有解决办法？

**Comment by Treri** [comment]
那可能就需要把主题单独放在一个repo中了.

比如我的博客 https://github.com/Treri/treri.github.io

在我本地, 有两个remote

```
➜  treri.github.io git:(master) git remote -v
origin	https://github.com/Treri/Treri.github.io.git (fetch)
origin	https://github.com/Treri/Treri.github.io.git (push)
theme	https://github.com/Treri/jekyll-theme-iLotus.git (fetch)
theme	https://github.com/Treri/jekyll-theme-iLotus.git (push)
```

当主题需要修改时,  我会在主题的repo中进行更新. 然后在我的博客中进行`git fetch theme`, 然后将主题的修改更新到博客中来. 当博客新增文章, 添加链接什么的, 就在博客的repo中进行修改.

即, 永远从 theme repo ==> blog repo 单向更新

**Comment by nephen** [comment]
恩，这个可以，huxpro有主题不？

**Comment by Huxpro** [comment]
@Treri  

Exactly!! That's why I make the [huxblog-boilerplate](https://github.com/Huxpro/huxpro.github.io#boilerplate-beta), which includes the boilerplate code and sample posts only. It won't be updated so frequently except the real feature release.

However...It kind of sucks since the sync work between two repos is not as easy as I consider so the boilerplate is a little delayed, But kind of stable.

The basic idea was first proposed in <https://github.com/Huxpro/huxpro.github.io/issues/9> with a similar requirement. Anyway, please give it a try and I am looking forward to more feedbacks
