### ISSUE TITLE
设置字体大小无效

### ISSUE THREAD

**Issue by maoruibin** [Huxpro/huxpro.github.io#57]
自己在设置 post-meta 的字体大小时，我看到原来是 16 px ,然后自己想改小，设置为 12 px，然后在 hux-blog.min.css 中找到对应的 css 位置，重新设置大小，设置后发现无效，但是通过 浏览器发现属性其实已经是 12 px 了。

不知道这怎么解释。

**Comment by Huxpro** [comment]
@maoruibin 

Can you provide your repo or online URL that demonstrates the issue?
The setting of each of the font-size may not as easy as you considered, since `*.min.css` is generated by `Gruntfile.js` with one of the most popular css-preprocesser LESS. So I recommend you to modify style under `less/` instead of compiled file, and don't forget to use `grunt watch` to help you do the auto-recompilation.

BTW, these is of absolutely no possibility that browser render a text different with the computed style assigned to it. You should ensure what you checkout is the computed style panel instead of the source code.

**Comment by maoruibin** [comment]
you mean is if i want to change some style,and i must use grunt ? maybe i should install grunt firstly ~ thanks

**Comment by Huxpro** [comment]
@maoruibin 

Not really. You sure can modify styles directly in  `*.css` or `*.min.css`. But since they are generated, It's not such clear that you can easily figure out how style cascade and compute. Also, It would be totally overwritten when you run grunt to re-compile less the next time, and It's of none convenience for you to merge the later release as well.

It's kind of common practice to use `npm` and stuff like `grunt/gulp/webpack` to deal with the dependency management and build process in the recent years of front-end world. So you had better to get used to those cool shit if you want to modify the theme

**Comment by maoruibin** [comment]
I know what you mean,and I will keep trying to use grunt/gulp/webpack, thanks you response ~

**Comment by maoruibin** [comment]
Thanks you advice ,and now when I installed grunt and plugins successfully,and run `grunt watch` it works very well.

**Comment by Huxpro** [comment]
Awesome, enjoy!

**Comment by HaoQChen** [comment]
Which font size is the size of article? There seem to be many font-size, I have tried many of them. But no one can change the font size of my article(not titles)

**Comment by Huxpro** [comment]
Checkout `*.less` files. You can also use browser devtool to inspect.
