### ISSUE TITLE
添加文章的时候tags不能用tab

### ISSUE THREAD

**Issue by yangyaofei** [Huxpro/huxpro.github.io#69]
具体就是:

	---
	layout:		post
	title:			"红红火火恍恍惚惚"
	subtitle:		" "
	date:		2015-02-10
	author:		"yangyaofei"
	tags:
	(这里)- jQuery
	    - web
	    - Pinterest
	    - Masonry
	---

括号的地方,如果用空格就可以,如果改成tab键,页面分分钟上西天~~不知道是什么bug,就是找不到页没关系,希望可以写在doc里让别人也知道.一下午啥事儿没干,控制变量找bug了......

**Comment by aar0u** [comment]
YAML 规定缩进不可以用tab。

http://yaml.org/spec/1.0/
4.2.1 Indentation

Tab characters are not allowed in indentation since different systems treat tabs differently. To maintain portability, YAML's tab policy is conservative; they shall not be used. Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces.

**Comment by Huxpro** [comment]
@aar0u Thanks!

**Comment by yangyaofei** [comment]
哦哦，傻x了，这都都不知道………😂
2016年4月23日 下午9:54，"aar0u" <notifications@github.com>写道：
